//Arthur

package variaveisEnum;

public enum Permissao {

    // Secretaria
    MATRICULAR_ALUNO,
    TRANSFERIR_ALUNO,
    CADASTRAR_RESPONSAVEL,
    GERENCIAR_TURMAS,
    CONTROLAR_DOCUMENTOS,
    EMITIR_HISTORICO,

    // Pedagógico
    LANCAR_NOTAS,
    LANCAR_FREQUENCIA,
    MONTAR_GRADE_CURRICULAR,
    ACOMPANHAR_DESEMPENHO,
    REGISTRAR_PLANO_AULA,
    GERAR_RELATORIO_PEDAGOGICO,

    // Direção
    GERENCIAR_FUNCIONARIOS,
    APROVAR_MATRICULAS,
    VISUALIZAR_DASHBOARDS,
    DEFINIR_CALENDARIO,
    GERENCIAR_COMUNICADOS,
    VISUALIZAR_INDICADORES;
}